# You can use this docker-compose file to build the container image from source
# and start it. Usually this is used for development purposes.
#
# Example:
# docker-compose -f docker-compose-dev.yml up
#

version: '3.0'

services:
  pfbex:
    build: .
    container_name: pfbex
    ports:
      - 8765:8765
    env_file:
      - user.env
